<div class="category-container">
	<div class="product product-games">
		<div class="product-title">
			<a href="/games-dan-musik.html"><span>Games dan Musik</span></a>
		</div>	
		{{block type="catalog/product_list" name="home.catalog.product.games" alias="products_games" category_id="9" column_count="5" num_products="5" template="showcustomproducts/all.phtml"}}
	</div>
	<div class="product product-handphone">
		<div class="product-title">
			<a href="/handphone.html"><span>Handphone</span></a>
		</div>	
		{{block type="catalog/product_list" name="home.catalog.product.handphone" alias="products_handphone" category_id="10" column_count="5" num_products="5" template="showcustomproducts/all.phtml"}}
	</div>
	<div class="product product-kosmetik">
		<div class="product-title">
			<a href="/kosmetik.html"><span>Kosmetik</span></a>
		</div>	
		{{block type="catalog/product_list" name="home.catalog.product.kosmetik" alias="products_kosmetik" category_id="11" column_count="5" num_products="5" template="showcustomproducts/all.phtml"}}
	</div>
	<div class="product product-laptop">
		<div class="product-title">
			<a href="/laptop.html"><span>Laptop</span></a>
		</div>	
		{{block type="catalog/product_list" name="home.catalog.product.laptop" alias="products_laptop" category_id="12" column_count="5" num_products="5" template="showcustomproducts/all.phtml"}}
	</div>
	<div class="product product-pakaian">
		<div class="product-title">
			<a href="/pakaian.html"><span>Pakaian</span></a>
		</div>	
		{{block type="catalog/product_list" name="home.catalog.product.pakaian" alias="products_pakaian" category_id="13" column_count="5" num_products="5" template="showcustomproducts/all.phtml"}}
	</div>
	<div class="product product-aksesoris">
		<div class="product-title">
			<a href="/aksesoris.html"><span>Aksesoris</span></a>
		</div>	
		{{block type="catalog/product_list" name="home.catalog.product.aksesoris" alias="products_aksesoris" category_id="8" column_count="5" num_products="5" template="showcustomproducts/all.phtml"}}
	</div>
	<div class="product product-sepatu">
		<div class="product-title">
			<a href="/sepatu.html"><span>Sepatu</span></a>
		</div>	
		{{block type="catalog/product_list" name="home.catalog.product.sepatu" alias="products_sepatu" category_id="14" column_count="5" num_products="5" template="showcustomproducts/all.phtml"}}
	</div>
	<div class="product product-tablet">
		<div class="product-title">
			<a href="/tablet.html"><span>Tablet</span></a>
		</div>	
		{{block type="catalog/product_list" name="home.catalog.product.tablet" alias="products_tablet" category_id="15" column_count="5" num_products="5" template="showcustomproducts/all.phtml"}}
	</div>
	<div class="product product-tas">
		<div class="product-title">
			<a href="/tas.html"><span>Tas</span></a>
		</div>	
		{{block type="catalog/product_list" name="home.catalog.product.tas" alias="products_tas" category_id="16" column_count="5" num_products="5" template="showcustomproducts/all.phtml"}}
	</div>
	<div class="product product-dslr">
		<div class="product-title">
			<a href="/dslr.html"><span>dslr</span></a>
		</div>	
		{{block type="catalog/product_list" name="home.catalog.product.dslr" alias="products_dslr" category_id="25" column_count="5" num_products="5" template="showcustomproducts/all.phtml"}}
	</div>
</div>