<?php
/**
 * Veritrans VT Web Model Standard
 *
 * @category   Mage
 * @package    vtweb/form.phtml
 * @author     Kisman Hong, plihplih.com
 * this template is rendered when Veritrans payment method is chosen. This is description about Veritrans Payment Method
 */
?>
<ul class="form-list" id="payment_form_<?php echo $this->getMethodCode() ?>" style="display:none;">
    <li>
	<img src="<?php echo $this->getSkinUrl('images/veritrans/icon-clickpay.png') ?>"/><br/>
        <?php echo Mage::helper('vtweb/data')->_getFormMessage();?>
    </li>
</ul>
