<h4><span>Kategori Belanja</span></h4>
<ul class="category-nav-primary">
    <?php
        $obj = new Mage_Catalog_Block_Navigation();
        $storeCategories = $obj->getStoreCategories();
        Mage::registry('current_category') ? $currentCategoryId = Mage::registry('current_category')->getId() : $currentCategoryId='';
        foreach ($storeCategories as $_category):
    ?>
			<?php $_categoryModel = Mage::getModel('catalog/category')->load($_category->getId());?>
            <li>
            	<?php if ($currentCategoryId == $_category->getId()): ?>
	            	<?php echo '&emsp;' . '<a href="' . $_categoryModel->getUrl() . '" class="current"><span>' .  $_category->getName() . '</span></a>' ?>
	            <?php else : ?>	
                	<?php echo '&emsp;' . '<a href="' . $_categoryModel->getUrl() . '"><span>' .  $_category->getName() . '</span></a>' ?>
            	<?php endif ?>	
            </li>
        <?php endforeach ?>
</ul>